import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, Code2, Menu, MoveUpRight, Sparkles, X } from 'lucide-react'
import './Home.css'

const services = [
  { number: '01', title: 'Brand systems', text: 'Make your ambition unmistakable—across every touchpoint, from the first impression to the everyday.', icon: Sparkles },
  { number: '02', title: 'Digital experiences', text: 'Turn complex services into clear, considered experiences that people choose and return to.', icon: MoveUpRight },
  { number: '03', title: 'Creative technology', text: 'Build the robust, elegant systems that take an ambitious idea from prototype to production.', icon: Code2 },
]
const faqs = [
  ['What kinds of teams do you work with?', 'We partner with ambitious organizations at pivotal moments: launching something new, evolving a category, or making a complicated offer easier to understand and use.'],
  ['Can Alice help us from strategy through launch?', 'Yes. Our teams bring strategy, design, and technology together in one connected process—so the thinking makes it all the way into the work.'],
  ['Where is Alice based?', 'We work with teams everywhere from our Los Angeles and New York studios, with a collaborative model built for distributed teams.'],
]

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [formOpen, setFormOpen] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  const openContact = () => { setSubmitted(false); setFormOpen(true); setMenuOpen(false) }
  return <main>
    <header className="site-header"><a className="wordmark" href="#top" aria-label="Alice home"><span className="mark">a</span><span>ALICE</span></a><nav className={menuOpen ? 'nav open' : 'nav'} aria-label="Main navigation"><a href="#work" onClick={() => setMenuOpen(false)}>Work</a><a href="#services" onClick={() => setMenuOpen(false)}>Expertise</a><a href="#about" onClick={() => setMenuOpen(false)}>About</a><a href="#insights" onClick={() => setMenuOpen(false)}>Insights</a><button className="nav-contact" onClick={openContact}>Start a project <ArrowRight size={15}/></button></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X/> : <Menu/>}</button></header>
    <section className="hero" id="top"><div className="hero-grid" aria-hidden="true"><i/><i/><i/><i/></div><div className="eyebrow"><span/> Independent design & technology company</div><h1>Make the<br/><em>possible</em> real.</h1><div className="hero-bottom"><p>We build brands, products, and digital experiences that move ambitious organizations forward.</p><button className="button button-dark" onClick={openContact}>Start a conversation <ArrowRight size={18}/></button></div><div className="hero-orb"><div className="orb-line"/><span>Scroll to discover</span></div></section>
    <section className="statement" id="about"><p className="section-kicker">What we believe</p><div className="statement-copy"><h2>Change does not happen by accident. <em>It happens by design.</em></h2><p>We bring strategy, creativity, and technical craft into radical collaboration with the people making change happen.</p></div></section>
    <section className="work" id="work"><div className="section-head"><div><p className="section-kicker">Selected work</p><h2>Ideas made<br/><em>tangible.</em></h2></div><a className="text-link" href="#contact">See all work <ArrowRight size={17}/></a></div><div className="project-grid"><article className="project project-navy"><div className="project-art orbit-art"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><b>re</b></div><div className="project-meta"><span>Reformation</span><span>Brand platform · Digital</span></div><h3>Fashion’s next chapter, in motion.</h3><a href="#contact" aria-label="View Reformation case study"><ArrowRight/></a></article><article className="project project-lime"><div className="project-art type-art"><span>WELL</span><span>BEING</span><i/></div><div className="project-meta"><span>Common Ground</span><span>Strategy · Identity · Experience</span></div><h3>A new language for living well.</h3><a href="#contact" aria-label="View Common Ground case study"><ArrowRight/></a></article><article className="project project-sand"><div className="project-art form-art"><div/><div/><div/></div><div className="project-meta"><span>Open Table</span><span>Product experience</span></div><h3>Making every table feel like an invitation.</h3><a href="#contact" aria-label="View Open Table case study"><ArrowRight/></a></article></div></section>
    <section className="services" id="services"><div className="services-intro"><p className="section-kicker">Where we make impact</p><h2>One connected<br/>way <em>forward.</em></h2><p>We pair the right thinking with the right making—at the right moment—to get you where you are going.</p></div><div className="service-list">{services.map(({number,title,text,icon: Icon}) => <article className="service" key={title}><span>{number}</span><Icon strokeWidth={1.5}/><div><h3>{title}</h3><p>{text}</p></div><a href="#contact" aria-label={`Learn about ${title}`}><ArrowRight size={19}/></a></article>)}</div></section>
    <section className="proof" id="insights"><div className="proof-card"><p className="section-kicker">Built for momentum</p><div className="stat"><strong>01</strong><p>Shared clarity around the opportunity.</p></div><div className="stat"><strong>02</strong><p>Designed and built in one connected team.</p></div><div className="people"><div className="faces"><i/><i/><i/></div><p>Built around your people, not a handoff.</p></div></div><div className="quote-card"><span className="quote-symbol">+</span><blockquote>Better outcomes begin when every discipline is part of the same conversation.</blockquote><div><b>Strategy, design & technology</b><span>Working together from first question to launch</span></div><a className="play" href="mailto:la@alice.inc">Start the conversation <ArrowRight size={20}/></a></div></section>
    <section className="faq"><div><p className="section-kicker">A good place to start</p><h2>Questions,<br/><em>answered.</em></h2></div><div className="faq-list">{faqs.map(([q,a], i) => <div className="faq-item" key={q}><button onClick={() => setOpenFaq(openFaq === i ? null : i)}>{q}<ChevronDown className={openFaq === i ? 'rotated' : ''}/></button>{openFaq === i && <p>{a}</p>}</div>)}</div></section>
    <section className="final-cta" id="contact"><p className="section-kicker">Have something in mind?</p><h2>Let’s make it<br/><em>matter.</em></h2><button className="round-button" onClick={openContact}>Start a project <ArrowRight size={22}/></button><div className="footer-line"><a href="mailto:la@alice.inc">la@alice.inc</a><a href="mailto:ny@alice.inc">ny@alice.inc</a><span>© 2025 Alice, Inc.</span><a href="#top">Back to top ↑</a></div></section>
    {formOpen && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="contact-modal"><button className="close" onClick={() => setFormOpen(false)} aria-label="Close"><X/></button>{submitted ? <div className="thanks"><span className="check-circle"><Check/></span><p className="section-kicker">Message received</p><h2>We’ll be in touch.</h2><p>Thank you for reaching out. A member of our team will respond shortly.</p><button className="button button-dark" onClick={() => setFormOpen(false)}>Close</button></div> : <><p className="section-kicker">Start a project</p><h2 id="dialog-title">Tell us what’s possible.</h2><p className="modal-copy">Share a little about your ambition. We will follow up within two business days.</p><form onSubmit={(e) => {e.preventDefault(); setSubmitted(true)}}><label>Name<input required placeholder="Your name"/></label><label>Work email<input type="email" required placeholder="you@company.com"/></label><label>What are you working on?<textarea required placeholder="A little context goes a long way" rows={3}/></label><button className="button button-dark" type="submit">Send inquiry <ArrowRight size={18}/></button></form></>}</div></div>}
  </main>
}
